# Generated by Django 5.2.4 on 2025-07-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Book',
        ),
    ]
